server:
  port: 9090

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
    customer-by-service:
      path: /customer-by-service/**
      serviceId: CUSTOMER-SERVICE
    static:
      path: /static/**
    oauth2:
      path: /uaa/**
      serviceId: oauth2
      stripPrefix: false

spring:
  aop:
    proxy-target-class: true
      
  
# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      internalApi: oauth2
      externalApi: none
      
security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9443/uaa/oauth/token
      userAuthorizationUri: http://localhost:9443/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9443/uaa/user
wso2SessionTerminateUrl: https://localhost:9443/commonauth?commonAuthLogout=true&type=oid&commonAuthCallerPath=http://localhost:8080/logout&relyingParty=localhost
